apiVersion: v1
kind: Service
metadata:
  name: cccms-api
  namespace: cccms
  labels:
    app: cccms-api
spec:
  selector:
    app: cccms-api
  ports:
    - name: http
      port: 5289
      targetPort: 5289
    - name: https
      port: 7261
      targetPort: 7261
  type: LoadBalancer
