apiVersion: v1
kind: ConfigMap
metadata:
  name: cccms-grafana-datasource
  namespace: cccms
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://cccms-prometheus:9090
        isDefault: true
        editable: true
