apiVersion: v1
kind: Service
metadata:
  name: cccms-grafana
  namespace: cccms
  labels:
    app: cccms-grafana
spec:
  selector:
    app: cccms-grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
