apiVersion: v1
kind: Service
metadata:
  name: cccms-prometheus
  namespace: cccms
  labels:
    app: cccms-prometheus
spec:
  selector:
    app: cccms-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  type: ClusterIP
