apiVersion: v1
kind: Secret
metadata:
  name: cccms-secrets
  namespace: cccms
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: "sa@123456789"
  CONNECTION_STRING: "Server=cccms-sqlserver,1433;Database=NciemsDb.Dev;User Id=sa;Password=sa@123456789;TrustServerCertificate=True;MultipleActiveResultSets=True"
