apiVersion: v1
kind: Service
metadata:
  name: cccms-sqlserver
  namespace: cccms
  labels:
    app: cccms-sqlserver
spec:
  selector:
    app: cccms-sqlserver
  ports:
    - name: tds
      port: 1433
      targetPort: 1433
  type: ClusterIP
