apiVersion: v1
kind: Service
metadata:
  name: {{ include "cccms.fullname" . }}-frontend
  labels:
    app: {{ include "cccms.fullname" . }}-frontend
spec:
  selector:
    app: {{ include "cccms.fullname" . }}-frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: 80
  type: {{ .Values.frontend.service.type }}
