{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cccms.fullname" . }}-grafana-secret
type: Opaque
stringData:
  GRAFANA_ADMIN_USER: {{ .Values.monitoring.grafana.adminUser | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.monitoring.grafana.adminPassword | quote }}
{{- end }}
