apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cccms.fullname" . }}-secrets
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: {{ .Values.sqlserver.saPassword | quote }}
  CONNECTION_STRING: {{ printf "Server=%s-sqlserver,%v;Database=%s;User Id=sa;Password=%s;TrustServerCertificate=True;MultipleActiveResultSets=True" (include "cccms.fullname" .) .Values.sqlserver.service.port .Values.sqlserver.database .Values.sqlserver.saPassword | quote }}
