{{- if .Values.sqlserver.enabled }}
{{- if .Values.sqlserver.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cccms.fullname" . }}-sqlserver-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sqlserver.persistence.size }}
  {{- if .Values.sqlserver.persistence.storageClassName }}
  storageClassName: {{ .Values.sqlserver.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
{{- end }}
